# Now You Code In Class: 
## Tricks of The Pandas Masters Volume I

We will try something a bit different for our Activity - A series of Pandas coding challenges!

Datasets we will use:

- https://raw.githubusercontent.com/mafudge/datasets/master/flights/sample-flights.csv
- https://raw.githubusercontent.com/mafudge/datasets/master/orders/sample-orders.csv

In [1]:
import pandas as pd
import numpy as np
from IPython.display import display
from ipywidgets import widgets, interact_manual

pd.set_option('display.max_colwidth', None)

## Reading a dataset into a dataframe.

The following code loads the airline flights dataset into the variable `flights`

In [7]:
flights = pd.read_csv(" https://raw.githubusercontent.com/mafudge/datasets/master/flights/sample-flights.csv")
flights.head()

,flight_number,departure_airport_code,arrival_airport_code,departure_date,arrival_date,departure_time,arrival_time,flight_duration,airline_name,aircraft_type
0,1350,KJP,VOG,2022-03-26,2022-03-07,5:04,23:25,10.96,United,Embraer E190
1,5381,FUN,POW,2022-11-01,2022-07-05,19:32,13:09,10.29,Southwest,Embraer E190
2,2892,ROR,COO,2022-11-09,2022-05-16,0:02,19:45,10.65,Delta,Boeing 747
3,2406,XGA,HCM,2022-01-09,2022-02-13,19:32,11:45,12.20,American,Boeing 737
4,1261,TDK,LKU,2022-02-07,2022-01-26,4:25,16:50,7.05,United,Boeing 737

In [3]:
# PROMPT 1 read orders data into variable called "orders" and display the first few rows
orders = pd.read_csv("https://raw.githubusercontent.com/mafudge/datasets/master/orders/sample-orders.csv")
orders.head()

,orderid,orderdate,custname,custemail,custcountry,orderstatus,ordertotal,ordercreditcard,ordershipvia,shippingtotal
0,2,2023-03-24,Frayda Pepperd,fpepperd0@sciencedaily.com,Canada,delivered,228.39,Discover,RPS,12.05
1,3,2020-02-23,Loy Siberry,lsiberry1@so-net.ne.jp,Canada,delivered,76.87,Discover,USPS,6.27
2,4,2022-04-28,Carree Henworth,NaN,Canada,pending,152.30,Discover,USPS,12.74
3,5,2019-11-22,Goldina Godsafe,ggodsafe3@dailymail.co.uk,United States,shipped,182.17,Amex,UPS,5.44
4,6,2022-05-03,Marris Chatten,mchatten4@csmonitor.com,Mexico,pending,208.28,Discover,RPS,2.16

## What does the data look like?

This code uses `info()` to get information about the columns and datatypes of the dataframe.

In [4]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   flight_number           1000 non-null   int64
 1   departure_airport_code  1000 non-null   object
 2   arrival_airport_code    1000 non-null   object
 3   departure_date          1000 non-null   object
 4   arrival_date            1000 non-null   object
 5   departure_time          1000 non-null   object
 6   arrival_time            1000 non-null   object
 7   flight_duration         1000 non-null   float64
 8   airline_name            993 non-null    object
 9   aircraft_type           1000 non-null   object
dtypes: float64(1), int64(1), object(8)
memory usage: 78.3+ KB

## What are the different aircraft names?

This code will use `value_counts()` to produce counts of the different aircraft names

In [8]:
flights["aircraft_type"].value_counts()

aircraft_type
Embraer E190    229
Boeing 777      217
Boeing 747      149
Airbus A350     141
Boeing 737      134
Airbus A320     130
Name: count, dtype: int64

In [9]:
orders.columns

Index(['orderid', 'orderdate', 'custname', 'custemail', 'custcountry',
       'orderstatus', 'ordertotal', 'ordercreditcard', 'ordershipvia',
       'shippingtotal'],
      dtype='object')

In [10]:
# PROMPT 3  - get the value counts for order status
orders['orderstatus'].value_counts()

orderstatus
delivered    584
shipped      210
pending      206
Name: count, dtype: int64

In [22]:
sorted(list(flights['airline_name'].dropna().unique()))

['American', 'Delta', 'Jetblue', 'Southwest', 'United']

## This prints a list of unique airline names

We use `unique()` on the series to get a unique list of value, and `dropna()` to get rid of the empty values.

In [11]:
airlines = sorted(list(flights['airline_name'].dropna().unique()))
print(airlines)

['American', 'Delta', 'Jetblue', 'Southwest', 'United']

In [23]:
# PROMPT 4 - get a unique list of the customer country
def dedupe_series(series: pd.Series) -> list:
    dedupe = sorted(list(series.dropna().unique()))
    return dedupe

In [27]:
dedupe_series(flights['aircraft_type'])
#flights.columns

['Airbus A320',
 'Airbus A350',
 'Boeing 737',
 'Boeing 747',
 'Boeing 777',
 'Embraer E190']

## Create a drop-down list of airlines.

this creates a drop-down selection widget based on the airline values

In [32]:
airlines = dedupe_series(flights['airline_name'])
airline_dropdown = widgets.Dropdown(options=airlines, description="Airline")
display(airline_dropdown)

Dropdown(description='Airline', options=('American', 'Delta', 'Jetblue', 'Southwest', 'United'), value='Americ…

In [39]:
# PROMPT 5 - create a dropdown of countries from orders
countries = dedupe_series(orders['custcountry'])
country_dropdown = widgets.Dropdown(options=countries, description="Pick a country:")
display(country_dropdown)

Dropdown(description='Pick a country:', options=('Canada', 'Mexico', 'United States'), value='Canada')

## Get stats on the numerical columns

The `describe()` method function will get statistics for the numerical values in the dataframe.

In [42]:
flights.describe()
# 95 percentile of flight_duration
flights['flight_duration'].quantile(0.95)

np.float64(15.100499999999998)

In [46]:
# PROMPT 6 - that is the least expensive order? Most expensive shipping amount?
orders.describe()

           orderid   ordertotal  shippingtotal
count  1000.000000  1000.000000     944.000000
mean    501.500000   150.688370      10.367352
std     288.819436    56.781819       5.259112
min       2.000000    50.140000       1.040000
25%     251.750000   103.535000       5.877500
50%     501.500000   150.845000      10.525000
75%     751.250000   198.552500      14.742500
max    1001.000000   249.190000      20.000000

In [47]:
mexican_orders = orders[ orders['custcountry'] == 'Mexico' ]
mexican_orders.describe()

           orderid  ordertotal  shippingtotal
count   216.000000  216.000000     209.000000
mean    493.814815  153.669954      10.490335
std     290.760915   58.156922       5.492066
min       6.000000   50.460000       1.120000
25%     244.250000  104.700000       5.150000
50%     489.000000  150.905000      10.800000
75%     711.000000  207.545000      15.470000
max    1000.000000  249.190000      20.000000

## Storing Min and Max in variables

This example stores the shortest and longest flights in separate variables.

In [48]:
shortest = flights['flight_duration'].min()
longest = flights['flight_duration'].max()
print(shortest, longest)

1.02 15.99

In [49]:
# PROMPT 7 - store the largest and smallest orders order total in variables.
smallest_order = orders['ordertotal'].min()
largest_order = orders['ordertotal'].max()
print(smallest_order, largest_order)

50.14 249.19

## Creating a Range Slider widget

This example creates a Range slider widget for flight duration, setting the upper and lower bounds to the min/max values.

In [53]:
flight_duration_slider = widgets.FloatRangeSlider(
    min = shortest, max=longest, step=0.5, description="Flight Duration")
display(flight_duration_slider)

FloatRangeSlider(value=(4.7625, 12.2475), description='Flight Duration', max=15.99, min=1.02, step=0.5)

In [ ]:
# PROMPT 8 - Create a range slider for orders using min/max approach
# you can do this on your own!

## Let's engineer a column!

This example will create a YEAR column by slicing the first 4 characters from the date. Since the data type of the `departure_date` is Object we must use the `.str` property to get the string value.

In [ ]:
"Lebron James - Lakers"
"Lebron James - Cavs"

In [54]:
flights.head()

,flight_number,departure_airport_code,arrival_airport_code,departure_date,arrival_date,departure_time,arrival_time,flight_duration,airline_name,aircraft_type
0,1350,KJP,VOG,2022-03-26,2022-03-07,5:04,23:25,10.96,United,Embraer E190
1,5381,FUN,POW,2022-11-01,2022-07-05,19:32,13:09,10.29,Southwest,Embraer E190
2,2892,ROR,COO,2022-11-09,2022-05-16,0:02,19:45,10.65,Delta,Boeing 747
3,2406,XGA,HCM,2022-01-09,2022-02-13,19:32,11:45,12.20,American,Boeing 737
4,1261,TDK,LKU,2022-02-07,2022-01-26,4:25,16:50,7.05,United,Boeing 737

In [55]:
# making the departure_year from the four of departure_date
flights["departure_year"] = flights["departure_date"].str[:4]
flights.head()

,flight_number,departure_airport_code,arrival_airport_code,departure_date,arrival_date,departure_time,arrival_time,flight_duration,airline_name,aircraft_type,departure_year
0,1350,KJP,VOG,2022-03-26,2022-03-07,5:04,23:25,10.96,United,Embraer E190,2022
1,5381,FUN,POW,2022-11-01,2022-07-05,19:32,13:09,10.29,Southwest,Embraer E190,2022
2,2892,ROR,COO,2022-11-09,2022-05-16,0:02,19:45,10.65,Delta,Boeing 747,2022
3,2406,XGA,HCM,2022-01-09,2022-02-13,19:32,11:45,12.20,American,Boeing 737,2022
4,1261,TDK,LKU,2022-02-07,2022-01-26,4:25,16:50,7.05,United,Boeing 737,2022

In [58]:
orders.head(n=2)

,orderid,orderdate,custname,custemail,custcountry,orderstatus,ordertotal,ordercreditcard,ordershipvia,shippingtotal
0,2,2023-03-24,Frayda Pepperd,fpepperd0@sciencedaily.com,Canada,delivered,228.39,Discover,RPS,12.05
1,3,2020-02-23,Loy Siberry,lsiberry1@so-net.ne.jp,Canada,delivered,76.87,Discover,USPS,6.27

In [60]:
# PROMPT 9 - create an order year column!
orders['orderyear'] = orders['orderdate'].str[:4]
orders[['orderyear','orderdate']].head(n=2)

  orderyear   orderdate
0      2023  2023-03-24
1      2020  2020-02-23

In [63]:
orders['orderyeatsgzvz'] = "hello"
orders[['orderyear','orderdate','orderyeatsgzvz']].head(n=2)

  orderyear   orderdate orderyeatsgzvz
0      2023  2023-03-24          hello
1      2020  2020-02-23          hello

In [64]:
# deleting a colum
del orders['orderyeatsgzvz']
orders.columns

Index(['orderid', 'orderdate', 'custname', 'custemail', 'custcountry',
       'orderstatus', 'ordertotal', 'ordercreditcard', 'ordershipvia',
       'shippingtotal', 'orderyear'],
      dtype='object')

In [70]:
# PROMPT 9.5 Clean up order status to use title case
"mike fudge".title()
orders['orderstatus'].unique()
orders['orderstatus_titlecase'] = orders['orderstatus'].str.title()
orders[['orderstatus','orderstatus_titlecase']].head(n=2)

  orderstatus orderstatus_titlecase
0   delivered             Delivered
1   delivered             Delivered

In [78]:
# prompt 10 - create an order month column!
# This shows you a couple of order dates
orders['orderdate'].values[:3]
# Where is the month how would you get it?
orders['ordermonth'] = orders['orderdate'].str[5:7]
orders[['orderdate','ordermonth']].head(n=3)

    orderdate ordermonth
0  2023-03-24         03
1  2020-02-23         02
2  2022-04-28         04

## United airlines flights

This example uses a boolean filter to create a smaller dataframe of just United airlines flights.

In [81]:
ua_flights = flights[
    flights["airline_name"] == "United"
]
ua_flights['airline_name'].value_counts()

airline_name
United    256
Name: count, dtype: int64

In [82]:
orders.columns

Index(['orderid', 'orderdate', 'custname', 'custemail', 'custcountry',
       'orderstatus', 'ordertotal', 'ordercreditcard', 'ordershipvia',
       'shippingtotal', 'orderyear', 'orderstatus_titlecase', 'ordermonth'],
      dtype='object')

In [83]:
# Prompt 10 - display only orders that were delivered
delivered_orders = orders[
    orders['orderstatus'] == 'delivered'
]
delivered_orders

,orderid,orderdate,custname,custemail,custcountry,orderstatus,ordertotal,ordercreditcard,ordershipvia,shippingtotal,orderyear,orderstatus_titlecase,ordermonth
0,2,2023-03-24,Frayda Pepperd,fpepperd0@sciencedaily.com,Canada,delivered,228.39,Discover,RPS,12.05,2023,Delivered,03
1,3,2020-02-23,Loy Siberry,lsiberry1@so-net.ne.jp,Canada,delivered,76.87,Discover,USPS,6.27,2020,Delivered,02
5,7,2022-12-19,Logan Jacobsson,ljacobsson5@wufoo.com,United States,delivered,112.15,Amex,USPS,11.52,2022,Delivered,12
7,9,2019-02-17,Lowrance Sigsworth,lsigsworth7@youtube.com,United States,delivered,141.94,Discover,USPS,7.31,2019,Delivered,02
9,11,2020-01-20,Renato Hue,rhue9@un.org,Canada,delivered,120.52,Visa,USPS,5.57,2020,Delivered,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,996,2019-04-03,Barty Bell,bbellrm@eepurl.com,United States,delivered,114.47,Discover,UPS,8.30,2019,Delivered,04
995,997,2023-09-22,Stewart Punter,spunterrn@yolasite.com,Canada,delivered,155.50,Visa,UPS,17.27,2023,Delivered,09
996,998,2019-02-23,Sherwynd Hardesty,shardestyro@deviantart.com,Mexico,delivered,245.48,Visa,UPS,19.86,2019,Delivered,02
997,999,2020-02-25,Doll Kristiansen,dkristiansenrp@ca.gov,Canada,delivered,163.07,Amex,FedEX,6.09,2020,Delivered,02
999,1001,2023-08-20,Ronna Crebott,rcrebottrr@cnet.com,United States,delivered,161.43,Discover,USPS,16.90,2023,Delivered,08

## Dataframe Boolean Filters with logical And

Sometimes you want to filter a dataframe on two conditions for example:


    - American Airlines AND
    - Boeing 777 aircraft

To do this we must use the dataframe AND operator: `&`

Notice how we must include `()` around each boolean filter.

In [85]:
# and or not
# &   |  ~
special_flights = flights[ 
    (flights["airline_name"] == "American") & 
    (flights["aircraft_type"] == "Boeing 777") 
]
special_flights.head()

,flight_number,departure_airport_code,arrival_airport_code,departure_date,arrival_date,departure_time,arrival_time,flight_duration,airline_name,aircraft_type,departure_year
21,2329,ELA,XPK,2022-08-01,2022-03-02,22:09,7:53,7.79,American,Boeing 777,2022
40,4116,ZLX,ASY,2022-03-01,2022-09-28,2:51,10:53,14.57,American,Boeing 777,2022
52,2567,DGF,OSP,2022-03-06,2022-08-21,13:38,22:22,14.65,American,Boeing 777,2022
78,9761,SDY,BSF,2022-05-02,2022-01-06,23:11,18:50,7.35,American,Boeing 777,2022
114,6574,GZP,FEB,2022-04-30,2022-09-10,6:32,13:48,15.44,American,Boeing 777,2022

In [ ]:
# PROMPT 11 - show "special orders": those orders delivered to the Canada in year 2023

## Flight Tracker

Inputs:

    - Range for the duration of the flight
    - Airline
    
Outputs:
    
    -DataFrame of flights matching that criteira

In [87]:
# Get Data
airlines = sorted(list(flights['airline_name'].dropna().unique()))
shortest = flights['flight_duration'].min()
longest = flights['flight_duration'].max()

# Make widgets
airline_dropdown = widgets.Dropdown(options=airlines, description="Airline")
flight_duration_slider = widgets.FloatRangeSlider(
    min = shortest, max=longest, step=0.5, description="Duration")

@interact_manual(airline=airline_dropdown, duration=flight_duration_slider)
def on_click(airline, duration):
    filtered_flights = flights[
        (flights["airline_name"] == airline) &
        (flights["flight_duration"] >= duration[0]) &
        (flights["flight_duration"] <= duration[1])
    ]
    display(filtered_flights)

interactive(children=(Dropdown(description='Airline', options=('American', 'Delta', 'Jetblue', 'Southwest', 'U…

## Order Report

Inputs:

    - Range Slider for the order amount total
    - Year of order, Order Status, Customer Country as drop downs
    
Outputs:
    
    -DataFrame of orders matching the selected criteria

In [ ]:
orders.columns # a refresher of the available columns

In [ ]:
# PROMPT 12 - make the order report!

# Get Data for widgets


# Make widgets


# main iteract

In [ ]:
# run this code to turn in your work!
from casstools.assignment import Assignment
Assignment().submit()