# Now You Code In Class: 

## Tricks of The Pandas Masters Volume II

Once again, we will try something a bit different for our Activity - A series of Pandas coding challenges!

Datasets we will use:

- Reddit Data: https://raw.githubusercontent.com/mafudge/datasets/master/json-samples/reddit.json
- Episodes of the HBO series "The Wire": https://raw.githubusercontent.com/mafudge/datasets/master/tv-shows/the-wire.json

In [4]:
import pandas as pd
import warnings

pd.set_option('display.max_colwidth', None)
warnings.filterwarnings('ignore')

## Deserializing json

the following function takes a URL as input and returns deserialized json as output.

In [5]:
def get_json(url: str):
    import requests
    response = requests.get(url)
    response.raise_for_status()
    return response.json()

This example deserializes reddit news and then finds the key where the articles are and displays the first artcle.

In [10]:
reddit = get_json("https://raw.githubusercontent.com/mafudge/datasets/master/json-samples/reddit.json")
articles = reddit["data"]["children"]
articles[1]

{'kind': 't3',
 'data': {'domain': 'cbc.ca',
  'banned_by': None,
  'media_embed': {},
  'subreddit': 'news',
  'selftext_html': None,
  'selftext': '',
  'likes': None,
  'suggested_sort': None,
  'user_reports': [],
  'secure_media': None,
  'link_flair_text': None,
  'id': '4bmzo9',
  'from_kind': None,
  'gilded': 0,
  'archived': False,
  'clicked': False,
  'report_reasons': None,
  'author': 'Duke28',
  'media': None,
  'score': 0,
  'approved_by': None,
  'over_18': False,
  'hidden': False,
  'num_comments': 1,
  'thumbnail': '',
  'subreddit_id': 't5_2qh3l',
  'hide_score': False,
  'edited': False,
  'link_flair_css_class': None,
  'author_flair_css_class': None,
  'downs': 0,
  'secure_media_embed': {},
  'saved': False,
  'removal_reason': None,
  'stickied': False,
  'from': None,
  'is_self': False,
  'from_id': None,
  'permalink': '/r/news/comments/4bmzo9/zika_outbreak_needs_4_million_who/',
  'locked': False,
  'name': 't3_4bmzo9',
  'created': 1458776277.0,
  'url': 'http://www.cbc.ca/news/health/zika-who-funds-1.3503095',
  'author_flair_text': None,
  'quarantine': False,
  'title': 'Zika outbreak needs $4 million: WHO',
  'created_utc': 1458747477.0,
  'distinguished': None,
  'mod_reports': [],
  'visited': False,
  'num_reports': None,
  'ups': 0}}

In [15]:
# PROMPT 1 read in episodes of "The Wire" find the episodes key, and show the first episode.
thewire = get_json("https://raw.githubusercontent.com/mafudge/datasets/master/tv-shows/the-wire.json")
thewire

{'id': 179,
 'url': 'https://www.tvmaze.com/shows/179/the-wire',
 'name': 'The Wire',
 'type': 'Scripted',
 'language': 'English',
 'genres': ['Drama', 'Crime'],
 'status': 'Ended',
 'runtime': 60,
 'averageRuntime': 60,
 'premiered': '2002-06-02',
 'ended': '2008-03-09',
 'officialSite': 'http://www.hbo.com/the-wire',
 'schedule': {'time': '21:00', 'days': ['Sunday']},
 'rating': {'average': 9.1},
 'weight': 95,
 'network': {'id': 8,
  'name': 'HBO',
  'country': {'name': 'United States',
   'code': 'US',
   'timezone': 'America/New_York'},
  'officialSite': 'https://www.hbo.com/'},
 'webChannel': None,
 'dvdCountry': None,
 'externals': {'tvrage': 6296, 'thetvdb': 79126, 'imdb': 'tt0306414'},
 'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_portrait/1/2527.jpg',
  'original': 'https://static.tvmaze.com/uploads/images/original_untouched/1/2527.jpg'},
 'summary': "<p>The first season of <b>The Wire</b> (2002) concentrated on the often-futile efforts of police to infiltrate a West Baltimore drug ring headed by Avon Barksdale and his lieutenant, Stringer Bell. In Seasons Two and Three, as the Barksdale investigation escalated, new storylines involving pressures on the working class and the city's political leadership were introduced. Season Four focused on the stories of several young boys in the public school system, struggling with problems at home and the lure of the corner - set against the rise of a new drug empire in West Baltimore and a new Mayor in City Hall. The fifth and final season of <i>The Wire</i> centers on the media's role in addressing - or failing to address - the fundamental political, economic and social realities depicted over the course of the series, while also resolving storylines of the numerous characters woven throughout the narrative arc of the show.</p>",
 'updated': 1644603937,
 '_links': {'self': {'href': 'https://api.tvmaze.com/shows/179'},
  'previousepisode': {'href': 'https://api.tvmaze.com/episodes/12969'}},
 '_embedded': {'episodes': [{'id': 12907,
    'url': 'https://www.tvmaze.com/episodes/12907/the-wire-1x01-the-target',
    'name': 'The Target',
    'season': 1,
    'number': 1,
    'type': 'regular',
    'airdate': '2002-06-02',
    'airtime': '21:00',
    'airstamp': '2002-06-03T01:00:00+00:00',
    'runtime': 60,
    'rating': {'average': 7.8},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/94/236937.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/94/236937.jpg'},
    'summary': '<p>Homicide detective Jimmy McNulty observes the murder trial of a mid-level drug dealer, D\'Angelo Barksdale, and sees the prosecution\'s star witness recant her testimony. McNulty recognises drug king-pin Stringer Bell in the court room and believes he has manipulated the proceedings, so he circumvents the chain-of-command by talking to the judge, Daniel Phelan, who then places pressure on the police department to investigate the Barksdale drug-dealing organization, which, McNulty claims, has gotten away with ten murders in the last year. D\'Angelo is welcomed home by his uncle, Barksdale patriarch, Avon, who is frustrated with him for placing himself in a situation where the police could charge him. Nevertheless, Avon allows him to return to work, but in what D\'Angelo sees as a demotion, he is moved to a low-rise housing project known as "the pit." Meanwhile, homeless drug addict Bubbles, acts as mentor to another addict, Johnny Weeks, in an ill-conceived scam with severe consequences.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/12907'}}},
   {'id': 12908,
    'url': 'https://www.tvmaze.com/episodes/12908/the-wire-1x02-the-detail',
    'name': 'The Detail',
    'season': 1,
    'number': 2,
    'type': 'regular',
    'airdate': '2002-06-09',
    'airtime': '21:00',
    'airstamp': '2002-06-10T01:00:00+00:00',
    'runtime': 60,
    'rating': {'average': 8.1},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/94/236928.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/94/236928.jpg'},
    'summary': '<p>The witness who testified against D\'Angelo is killed and the Barksdale organization is suspected. In light of Phelan\'s pressure, a detail is formed to investigate their activity in the towers and the pit. However, the detail\'s lieutenant, Cedric Daniels, is concerned with the quality of the team assigned by Deputy Ops. Ervin Burrell, while McNulty is concerned with the department\'s plan for the investigation, believing the approach of "buy busts" won\'t get them anywhere near the high-ranking members of the organization. The operation begins with Daniels\' protégé Kima Greggs using Bubbles to identify who\'s who on the street. Meanwhile, McNulty and his partner, Bunk, try an unusual interrogation approach with D\'Angelo, while Burrell tries to keep the death of the witness out of the press. Later, Daniels\' suspicions about his team prove correct when an unauthorized late night foray into the towers by Herc, Carver and Prez goes awry.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/12908'}}},
   {'id': 12909,
    'url': 'https://www.tvmaze.com/episodes/12909/the-wire-1x03-the-buys',
    'name': 'The Buys',
    'season': 1,
    'number': 3,
    'type': 'regular',
    'airdate': '2002-06-16',
    'airtime': '21:00',
    'airstamp': '2002-06-17T01:00:00+00:00',
    'runtime': 60,
    'rating': {'average': 8.2},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/94/236930.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/94/236930.jpg'},
    'summary': '<p>"The king stay the king." - D\'AngeloAfter early morning "field interviews" conducted by Herc, Carver and Prez lead to a minor riot and bad publicity for the police, Daniels gets called in by the Deputy Commissioner. McNulty sends Mahone and Polk to the terrace to get a photo of Avon Barksdale. They come up short but soft- spoken Freamon comes through with an old photo from Barksdale\'s boxing days. McNulty and Greggs visit FBI agent Fitzhugh to try and obtain some surveillance equipment. D\'Angelo delivers the daily count to Stringer Bell who in turn, gives D\'Angelo a bonus. Later, while Bodie and D\'Angelo wait for the new supply to arrive, D\'Angelo offers to get food. While he\'s gone Bodie, Stinkum and the crew go to retrieve the new supply only renegade dealer Omar and his crew get there and steal the drugs for themselves. The next day D\'Angelo gets chewed out by Wee Bey -- a Barksdale enforcer -- for not being around when the incident happened. After getting chided by his superiors, Lieutenant Daniels mobilizes the team to raid "The Pit". Bodie hits one of the detectives while getting arrested and the rest of the officers proceed to beat Bodie. McNulty secretly meets with agent Fitzhugh who tells him to watch out for Lieutenant Daniels -- who might be on the take.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/12909'}}},
   {'id': 12910,
    'url': 'https://www.tvmaze.com/episodes/12910/the-wire-1x04-old-cases',
    'name': 'Old Cases',
    'season': 1,
    'number': 4,
    'type': 'regular',
    'airdate': '2002-06-23',
    'airtime': '21:00',
    'airstamp': '2002-06-24T01:00:00+00:00',
    'runtime': 60,
    'rating': {'average': 8.5},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/25/63545.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/25/63545.jpg'},
    'summary': "<p>Bodie wakes up from his injuries in a Washington, D.C. juvenile detention center and manages to escape just before Herc and Carver arrive to interrogate him. Avon discusses the loss of the pit's stash with his enforcers and marks Omar and his crew for death. McNulty and his partner from homicide Bunk Moreland investigate an old murder that may be related to D'Angelo.</p>",
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/12910'}}},
   {'id': 12911,
    'url': 'https://www.tvmaze.com/episodes/12911/the-wire-1x05-the-pager',
    'name': 'The Pager',
    'season': 1,
    'number': 5,
    'type': 'regular',
    'airdate': '2002-06-30',
    'airtime': '21:00',
    'airstamp': '2002-07-01T01:00:00+00:00',
    'runtime': 60,
    'rating': {'average': 8.3},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/94/236932.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/94/236932.jpg'},
    'summary': '<p>Avon Barksdale Avon becomes more and more suspicious, he orders Wee-Bey to change phone lines in his apartment and promotes Stinkum to manage a new territory. He gets word that one of Omar\'s crew members has been "got". Stringer Bell warns D\'Angelo that a snitch may be in his camp. The detectives get their affidavit approved for a cloned pager but they are puzzled when the numbers they receive are not regular Baltimore phone numbers.. Herc and Carver catch up with Bodie and attempt to interrogate him.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/12911'}}},
   {'id': 12912,
    'url': 'https://www.tvmaze.com/episodes/12912/the-wire-1x06-the-wire',
    'name': 'The Wire',
    'season': 1,
    'number': 6,
    'type': 'regular',
    'airdate': '2002-07-07',
    'airtime': '21:00',
    'airstamp': '2002-07-08T01:00:00+00:00',
    'runtime': 60,
    'rating': {'average': 8.5},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/94/236933.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/94/236933.jpg'},
    'summary': '<p><i>"...and all the pieces matter." - Freamon</i><br />Brandon\'s bloodied body is discovered in the pit. Wallace gets even more unsettled about the situation after Avon rewards him for his part in Brandon\'s murder. The detail gets a wiretap running. Daniels clashes with homicide MajorWilliam Rawlsover their approach to the evidence they have gathered thus far.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/12912'}}},
   {'id': 12913,
    'url': 'https://www.tvmaze.com/episodes/12913/the-wire-1x07-one-arrest',
    'name': 'One Arrest',
    'season': 1,
    'number': 7,
    'type': 'regular',
    'airdate': '2002-07-21',
    'airtime': '21:00',
    'airstamp': '2002-07-22T01:00:00+00:00',
    'runtime': 60,
    'rating': {'average': 8.6},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/51/128682.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/51/128682.jpg'},
    'summary': '<p><i>"A man must have a code." - Bunk</i><br />Using information from the wiretap Detectives Greggs, Herc, Carver, andSydnorcatch a runner on his way to the pit with a re-supply. Avon worries about a possible snitch and Stringer confounds the detail\'s investigative efforts by cautiously instructing his people to stop using payphones. Rawls pressures his detective in the detail for information on their case.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/12913'}}},
   {'id': 12914,
    'url': 'https://www.tvmaze.com/episodes/12914/the-wire-1x08-lessons',
    'name': 'Lessons',
    'season': 1,
    'number': 8,
    'type': 'regular',
    'airdate': '2002-07-28',
    'airtime': '21:00',
    'airstamp': '2002-07-29T01:00:00+00:00',
    'runtime': 60,
    'rating': {'average': 8.7},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/51/129301.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/51/129301.jpg'},
    'summary': '<p><i>"Come at the king, you best not miss." - Omar</i><br />McNulty uses his children to tail Stringer after a chance encounter in a local market. Greggs and Carver arrest a driver picking up a large amount of cash from the Towers from known gang members, but are forced to return the money when the driver\'s political connections to Senator Clay Davis are revealed. Daniels discusses his problems following the money trail with his wife Marla.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/12914'}}},
   {'id': 12915,
    'url': 'https://www.tvmaze.com/episodes/12915/the-wire-1x09-game-day',
    'name': 'Game Day',
    'season': 1,
    'number': 9,
    'type': 'regular',
    'airdate': '2002-08-04',
    'airtime': '21:00',
    'airstamp': '2002-08-05T01:00:00+00:00',
    'runtime': 60,
    'rating': {'average': 8.6},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/51/129304.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/51/129304.jpg'},
    'summary': '<p><i>"Maybe we won." - Herc</i><br />Freamon gets Sydnor and Prez started on the Barksdale money trail. Omar gives East side kingpin Proposition Joe a stolen package for the opportunity to parley with him. Avon and Proposition Joe host an East side vs. West side basketball game, giving the detectives the first glimpse of their elusive target. Omar attempts to kill Avon, but is himself wounded.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/12915'}}},
   {'id': 12917,
    'url': 'https://www.tvmaze.com/episodes/12917/the-wire-1x10-the-cost',
    'name': 'The Cost',
    'season': 1,
    'number': 10,
    'type': 'regular',
    'airdate': '2002-08-11',
    'airtime': '21:00',
    'airstamp': '2002-08-12T01:00:00+00:00',
    'runtime': 60,
    'rating': {'average': 9},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/51/129948.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/51/129948.jpg'},
    'summary': '<p><i>"And then he dropped the bracelets..." - Greggs</i><br />After being clean for three days, Bubbles gets some strong advice from a former addict. Avon and Stringer tighten up ship following Omar\'s attempted hit on Avon. The detail identifies a major Barksdale stash house and an undercover operation has terrible consequences. Omar and Stringer Bell meet for a parley.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/12917'}}},
   {'id': 12918,
    'url': 'https://www.tvmaze.com/episodes/12918/the-wire-1x11-the-hunt',
    'name': 'The Hunt',
    'season': 1,
    'number': 11,
    'type': 'regular',
    'airdate': '2002-08-18',
    'airtime': '21:00',
    'airstamp': '2002-08-19T01:00:00+00:00',
    'runtime': 60,
    'rating': {'average': 9},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/52/131487.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/52/131487.jpg'},
    'summary': '<p><i>"Dope on the damn table." - Daniels</i><br />While Greggs\' life hangs in the balance, Daniels is ordered to raid the Barksdale operation. The detail\'s hand is forced and a series of city-wide raids and arrests are made to appease the Commissioner\'s desire for "dope on the table". Bubbles unwittingly implicates himself in the shooting.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/12918'}}},
   {'id': 12919,
    'url': 'https://www.tvmaze.com/episodes/12919/the-wire-1x12-cleaning-up',
    'name': 'Cleaning Up',
    'season': 1,
    'number': 12,
    'type': 'regular',
    'airdate': '2002-09-01',
    'airtime': '21:00',
    'airstamp': '2002-09-02T01:00:00+00:00',
    'runtime': 60,
    'rating': {'average': 8.7},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/52/131495.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/52/131495.jpg'},
    'summary': '<p><i>"This is me, yo, right here." - Wallace</i><br />Avon and Stringer meet with their attorney,Maurice Levy, to discuss a potential leak in the wake of the raids. Wallace goes back to the pit and asks to be let back in but Stringer has another plan. With the loss of their wiretaps the detail takes a fresh approach and installs a camera in Avon\'s club. They catch Avon discussing a drug run with D\'Angelo and arrest him en route.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/12919'}}},
   {'id': 12920,
    'url': 'https://www.tvmaze.com/episodes/12920/the-wire-1x13-sentencing',
    'name': 'Sentencing',
    'season': 1,
    'number': 13,
    'type': 'regular',
    'airdate': '2002-09-08',
    'airtime': '21:00',
    'airstamp': '2002-09-09T01:00:00+00:00',
    'runtime': 60,
    'rating': {'average': 8.9},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/52/132400.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/52/132400.jpg'},
    'summary': '<p><i>"all in the game..." - Traditional, West Baltimore</i><br />Daniels and McNulty\'s evidence of political corruption is of slight interest to the FBI, but the unit decides not to turn over the case to the FBI, but to pursue other directions, so that those involved in the drug trade are arrested or taken off the street. Daniels and McNulty face the ire of their superiors for flouting orders for a quick resolution to the case. D\'Angelo is convinced to stand with his family after a visit from his mother. The detail has enough information to arrest Avon and many of his people but Stringer is left on the street. Business resumes in the pit with Bodie and Poot leading the way.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/12920'}}},
   {'id': 12921,
    'url': 'https://www.tvmaze.com/episodes/12921/the-wire-2x01-ebb-tide',
    'name': 'Ebb Tide',
    'season': 2,
    'number': 1,
    'type': 'regular',
    'airdate': '2003-06-01',
    'airtime': '21:00',
    'airstamp': '2003-06-02T01:00:00+00:00',
    'runtime': 60,
    'rating': {'average': 7.6},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/94/236941.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/94/236941.jpg'},
    'summary': '<p><i>"Ain\'t never gonna be what it was." – Little Big Roy</i><br />Jimmy McNulty is sidelined to harbor patrol. He discovers a corpse in the harbor and pays back Colonel Rawls by proving City Homicide bear responsibility for the investigation.Major Valchek feels slighted when the boss of a local stevedore union named Frank Sobotka donates a more impressive gift to a local Polish church. Sobotka meets with other union leaders and learns that a crucial pier is still in a state of disrepair. Sobotka instructs his nephew Nick to see The Greek regarding payment for a clandestine container that he is smuggling through the port. Later, Port Police Officer "Beadie" Russell stumbles across The Greek\'s container and discovers the bodies of over a dozen young women inside.</p>',
    '_links': {'self': {'href': 'https://api.tvmaze.com/episodes/12921'}}},
   {'id': 12922,
    'url': 'https://www.tvmaze.com/episodes/12922/the-wire-2x02-collateral-damage',
    'name': 'Collateral Damage',
    'season': 2,
    'number': 2,
    'type': 'regular',
    'airdate': '2003-06-08',
    'airtime': '21:00',
    'airstamp': '2003-06-09T01:00:00+00:00',
    'runtime': 60,
    'rating': {'average': 8.5},
    'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_landscape/94/236942.jpg',
     'original': 'https://static.tvmaze.com/uploads/images/original_untouched/94/236942.jpg'},

## Creaating dataframe

In this example we use`json_normalize()` to display the articles in a dataframe

In [18]:
art_df = pd.json_normalize(articles) #articles is a list of dict!
art_df.head(1)

,kind,data.domain,data.banned_by,data.subreddit,data.selftext_html,data.selftext,data.likes,data.suggested_sort,data.user_reports,data.secure_media,...,data.url,data.author_flair_text,data.quarantine,data.title,data.created_utc,data.distinguished,data.mod_reports,data.visited,data.num_reports,data.ups
0,t3,wdrb.com,None,news,None,,None,None,[],None,...,http://www.wdrb.com/story/31546565/man-arrested-for-stealing-suv-told-police-he-needed-it-for-job-interview,None,False,Man arrested for stealing SUV told police he needed it for job interview,1.458748e+09,None,[],False,None,1

In [29]:
# # PROMPT 2 display the episodes as a dataframe
# wire_df = pd.json_normalize(thewire)
# wire_df
episodes_df = pd.json_normalize(thewire, record_path = ["_embedded","episodes"])
episodes_df.head()

,id,url,name,season,number,type,airdate,airtime,airstamp,runtime,summary,rating.average,image.medium,image.original,_links.self.href
0,12907,https://www.tvmaze.com/episodes/12907/the-wire-1x01-the-target,The Target,1,1,regular,2002-06-02,21:00,2002-06-03T01:00:00+00:00,60,"<p>Homicide detective Jimmy McNulty observes the murder trial of a mid-level drug dealer, D'Angelo Barksdale, and sees the prosecution's star witness recant her testimony. McNulty recognises drug king-pin Stringer Bell in the court room and believes he has manipulated the proceedings, so he circumvents the chain-of-command by talking to the judge, Daniel Phelan, who then places pressure on the police department to investigate the Barksdale drug-dealing organization, which, McNulty claims, has gotten away with ten murders in the last year. D'Angelo is welcomed home by his uncle, Barksdale patriarch, Avon, who is frustrated with him for placing himself in a situation where the police could charge him. Nevertheless, Avon allows him to return to work, but in what D'Angelo sees as a demotion, he is moved to a low-rise housing project known as ""the pit."" Meanwhile, homeless drug addict Bubbles, acts as mentor to another addict, Johnny Weeks, in an ill-conceived scam with severe consequences.</p>",7.8,https://static.tvmaze.com/uploads/images/medium_landscape/94/236937.jpg,https://static.tvmaze.com/uploads/images/original_untouched/94/236937.jpg,https://api.tvmaze.com/episodes/12907
1,12908,https://www.tvmaze.com/episodes/12908/the-wire-1x02-the-detail,The Detail,1,2,regular,2002-06-09,21:00,2002-06-10T01:00:00+00:00,60,"<p>The witness who testified against D'Angelo is killed and the Barksdale organization is suspected. In light of Phelan's pressure, a detail is formed to investigate their activity in the towers and the pit. However, the detail's lieutenant, Cedric Daniels, is concerned with the quality of the team assigned by Deputy Ops. Ervin Burrell, while McNulty is concerned with the department's plan for the investigation, believing the approach of ""buy busts"" won't get them anywhere near the high-ranking members of the organization. The operation begins with Daniels' protégé Kima Greggs using Bubbles to identify who's who on the street. Meanwhile, McNulty and his partner, Bunk, try an unusual interrogation approach with D'Angelo, while Burrell tries to keep the death of the witness out of the press. Later, Daniels' suspicions about his team prove correct when an unauthorized late night foray into the towers by Herc, Carver and Prez goes awry.</p>",8.1,https://static.tvmaze.com/uploads/images/medium_landscape/94/236928.jpg,https://static.tvmaze.com/uploads/images/original_untouched/94/236928.jpg,https://api.tvmaze.com/episodes/12908
2,12909,https://www.tvmaze.com/episodes/12909/the-wire-1x03-the-buys,The Buys,1,3,regular,2002-06-16,21:00,2002-06-17T01:00:00+00:00,60,"<p>""The king stay the king."" - D'AngeloAfter early morning ""field interviews"" conducted by Herc, Carver and Prez lead to a minor riot and bad publicity for the police, Daniels gets called in by the Deputy Commissioner. McNulty sends Mahone and Polk to the terrace to get a photo of Avon Barksdale. They come up short but soft- spoken Freamon comes through with an old photo from Barksdale's boxing days. McNulty and Greggs visit FBI agent Fitzhugh to try and obtain some surveillance equipment. D'Angelo delivers the daily count to Stringer Bell who in turn, gives D'Angelo a bonus. Later, while Bodie and D'Angelo wait for the new supply to arrive, D'Angelo offers to get food. While he's gone Bodie, Stinkum and the crew go to retrieve the new supply only renegade dealer Omar and his crew get there and steal the drugs for themselves. The next day D'Angelo gets chewed out by Wee Bey -- a Barksdale enforcer -- for not being around when the incident happened. After getting chided by his superiors, Lieutenant Daniels mobilizes the team to raid ""The Pit"". Bodie hits one of the detectives while getting arrested and the rest of the officers proceed to beat Bodie. McNulty secretly meets with agent Fitzhugh who tells him to watch out for Lieutenant Daniels -- who might be on the take.</p>",8.2,https://static.tvmaze.com/uploads/images/medium_landscape/94/236930.jpg,https://static.tvmaze.com/uploads/images/original_untouched/94/236930.jpg,https://api.tvmaze.com/episodes/12909
3,12910,https://www.tvmaze.com/episodes/12910/the-wire-1x04-old-cases,Old Cases,1,4,regular,2002-06-23,21:00,2002-06-24T01:00:00+00:00,60,"<p>Bodie wakes up from his injuries in a Washington, D.C. juvenile detention center and manages to escape just before Herc and Carver arrive to interrogate him. Avon discusses the loss of the pit's stash with his enforcers and marks Omar and his crew for death. McNulty and his partner from homicide Bunk Moreland investigate an old murder that may be related to D'Angelo.</p>",8.5,https://static.tvmaze.com/uploads/images/medium_landscape/25/63545.jpg,https://static.tvmaze.com/uploads/images/original_untouched/25/63545.jpg,https://api.tvmaze.com/episodes/12910
4,12911,https://www.tvmaze.com/episodes/12911/the-wire-1x05-the-pager,The Pager,1,5,regular,2002-06-30,21:00,2002-07-01T01:00:00+00:00,60,"<p>Avon Barksdale Avon becomes more and more suspicious, he orders Wee-Bey to change phone lines in his apartment and promotes Stinkum to manage a new territory. He gets word that one of Omar's crew members has been ""got"". Stringer Bell warns D'Angelo that a snitch may be in his camp. The detectives get their affidavit approved for a cloned pager but they are puzzled when the numbers they receive are not regular Baltimore phone numbers.. Herc and Carver catch up with Bodie and attempt to interrogate him.</p>",8.3,https://static.tvmaze.com/uploads/images/medium_landscape/94/236932.jpg,https://static.tvmaze.com/uploads/images/original_untouched/94/236932.jpg,https://api.tvmaze.com/episodes/12911

In [30]:
episodes_df.to_csv("the_wire_episodes.csv") # save it
eps = pd.read_csv("the_wire_episodes.csv")  # load it back up

## A Text Sentiment Web Service

The following function uses the http://text-processing.com service to calculate the sentiment for any input text. The result is a dict with probabilities and overall sentiment. For example:

INPUT: `"very nice"`

OUTPUT: 
```
{
    'probability': {
        'neg': 0.28997418956645504,
        'neutral': 0.13591527211268692,
        'pos': 0.710025810433545
    },
    'label': 'pos'
}

In [31]:
def get_text_sentiment(text: str) -> dict:
    import requests
    response = requests.post(
        "http://text-processing.com/api/sentiment/", 
        data={"text": text},
        headers={"User-Agent": "Mozillia/5.0"}
    )
    response.raise_for_status()
    return response.json()

# Use this "mocked" service if the real one is not available
def get_text_sentiment(text: str) -> dict:
    import random
    return random.choice(["Positive", "Negative", "Neutral"])


sentiment = get_text_sentiment("very nice")
sentiment

'Positive'

In [ ]:
# PROMPT 3: get the sentiment of the text below and print the label only
Tom owes me $5 but he owes jim $10

## Using a lambda with `apply()`

The following example creates a new Series in the dataframe called `"title_sentiment"` which calculates the sentiment of the reddit news title.

In [36]:
# new column = apply (lambda row: some function using row, axis=1)
art_df["title_sentiment"] = art_df.apply(lambda row: get_text_sentiment(row["data.title"]), axis=1)
art_df[["data.title", "title_sentiment"]].head()

,data.title,title_sentiment
0,Man arrested for stealing SUV told police he needed it for job interview,Neutral
1,Zika outbreak needs $4 million: WHO,Negative
2,"Austin police to fire officer who shot, killed nude teen",Neutral
3,Hubble Unveils Monster Stars,Neutral
4,ISIS application forms surface in intelligence haul on terror group's recruits,Negative

In [35]:
# PROMPT 4 get the sentiment for the summary Series in the episodes dataframe, name the column "summary_sentiment" and show the summary and the sentiment
episodes_df['summary_sentiment'] = episodes_df.apply(
    lambda row:get_text_sentiment(row['summary']), 
    axis=1)
episodes_df[['summary','summary_sentiment']].tail()

,summary,summary_sentiment
55,"<p>Mystified by Omar's disappearance, Marlo and Chris ramp up their efforts to locate their nemesis. After a sparsely attended waterfront ceremony, Carcetti fires away at a larger press event--and recasts himself as a champion for the homeless.</p>",Neutral
56,<p>An unexpected call puts Templeton back in the spotlight--and gets McNulty more attention than he expected. Bunk bucks at Landsman when ordered to help with the force's most recent red ball.</p>,Negative
57,"<p>Baltimore's renewed police commitment brings fresh recruits to Daniels and McNulty, starting with Carver. Facing a new political challenge, Carcetti is forced to make dangerous political deals.</p>",Neutral
58,"<p>With Steintorf ordering Rawls to initiate 'creative' remedies for the rising crime rate, Freamon's vigilance pays off with a promising lead, sending Sydnor and the department into overdrive.</p>",Neutral
59,<p>Carcetti maps out a damage-control scenario with the police brass in the wake of a startling revelation from Pearlman and Daniels. Their choice: clean up the mess...or hide the dirt.</p>,Neutral

## Saving the dataframe 

Calculating the sentiment isn't free and we don't need to do it more than once. Its a good idea to save the content of our dataframe at this point.  That way we can continue from the saved file versus re-calculating the transformation.

After you run this code open the `reddit_news_articles.csv` file and check it out!

In [ ]:
art_df.to_csv("reddit_news_articles.csv", index=False)

In [37]:
# PROMPT 5 save your episodes of the wire to "the_wire_episodes.csv"
episodes_df.to_csv("cheese/wire_episodes.csv")

## Hot and Top articles.

You have been hired as a data scientist at Reddit. Through your extensive statistical research, you have determined: 

- Articles where the number of comments are in the 75% percentile should be categorized as `"Hot"`
- Articles where the number of upvotes are in the 75% percentile should be categorized as `"Popular"`
- Articles matching both should be categories as `"Fire"`

In these next challenges, we will write code to implement these rules.

In [44]:
art_df.columns

Index(['kind', 'data.domain', 'data.banned_by', 'data.subreddit',
       'data.selftext_html', 'data.selftext', 'data.likes',
       'data.suggested_sort', 'data.user_reports', 'data.secure_media',
       'data.link_flair_text', 'data.id', 'data.from_kind', 'data.gilded',
       'data.archived', 'data.clicked', 'data.report_reasons', 'data.author',
       'data.media', 'data.score', 'data.approved_by', 'data.over_18',
       'data.hidden', 'data.num_comments', 'data.thumbnail',
       'data.subreddit_id', 'data.hide_score', 'data.edited',
       'data.link_flair_css_class', 'data.author_flair_css_class',
       'data.downs', 'data.saved', 'data.removal_reason', 'data.stickied',
       'data.from', 'data.is_self', 'data.from_id', 'data.permalink',
       'data.locked', 'data.name', 'data.created', 'data.url',
       'data.author_flair_text', 'data.quarantine', 'data.title',
       'data.created_utc', 'data.distinguished', 'data.mod_reports',
       'data.visited', 'data.num_reports', 'data.ups', 'title_sentiment'],
      dtype='object')

In [45]:
# PROMPT 6 write code to show the statistics of the numerical columns in the `art_df`
art_df.describe()

11.0 27.0

In [ ]:
# PROMPT 7 which columns represent comments? upvotes? What are the thresholds based on the 75% percentile?
hot = art_df['data.num_comments'].quantile(0.75)
pop = art_df['data.ups'].quantile(0.75) # top 75% percentile
print(hot, pop)

In [48]:
# PROMPT 8 Write code to extract the comments_threshold
def is_it_hot(num_comments, pct):
    '''
        example 
            is_it_hot(100, 15) == "Hot"
            is_it_hot(0, 15) == ""
    '''
    if num_comments >= pct:
        return "Hot"
    else:
        return ""

# test it!
print( is_it_hot(15,15) == "Hot" ) # Should be True

# Now we apply to data frame
art_df['catgor

True

In [ ]:
# PROMPT 9 Write code to extract the upvote_threshold

### defining the `categorize()` function:

Let's review the requirements: 

- Articles where the number of comments are in the 75% percentile should be categorized as "Hot"
- Articles where the number of upvotes are in the 75% percentile should be categorized as "Popular"
- Articles matching both should be categories as "Fire"

INPUTS (4): 

    PROMPT 10:
    num_comments, upvotes, comment_threshold, upvote_theshold
    
OUTPUTS (1):

    PROMPT 11
    "Hot", "Popular", "Fire" or ""

In [ ]:
# PROMPT 12 write function definition

In [ ]:
# PROMPT 13a write test for "Hot"
upvotes = 0
upvote_threshold = 0
comments = 0
comments_threshold = 0
expect = "????"
actual = categorize(upvotes, upvote_threshold, comments, comments_threshold)
print(f"When upvotes={upvotes}/{upvote_threshold}, comments={comments}/{comments_threshold}, EXPECT={expect}, ACTUAL={actual}")
assert expect == actual

In [ ]:
# PROMPT 13b write test for "Popular"
upvotes = 0
upvote_threshold = 0
comments = 0
comments_threshold = 0
expect = "????"
actual = categorize(upvotes, upvote_threshold, comments, comments_threshold)
print(f"When upvotes={upvotes}/{upvote_threshold}, comments={comments}/{comments_threshold}, EXPECT={expect}, ACTUAL={actual}")
assert expect == actua

In [ ]:
# PROMPT 13c write test for "Fire"
upvotes = 0
upvote_threshold = 0
comments = 0
comments_threshold = 0
expect = "????"
actual = categorize(upvotes, upvote_threshold, comments, comments_threshold)
print(f"When upvotes={upvotes}/{upvote_threshold}, comments={comments}/{comments_threshold}, EXPECT={expect}, ACTUAL={actual}")
assert expect == actua

In [ ]:
# PROMPT 13d write test for ""
upvotes = 0
upvote_threshold = 0
comments = 0
comments_threshold = 0
expect = "????"
actual = categorize(upvotes, upvote_threshold, comments, comments_threshold)
print(f"When upvotes={upvotes}/{upvote_threshold}, comments={comments}/{comments_threshold}, EXPECT={expect}, ACTUAL={actual}")
assert expect == actua

## Final step. lambda / apply

Add a column to the dataframe called `"category"` which calculates the category for the article 

output the article title, the number of comments, number of upvotes and the category

In [ ]:
# PROMPT 14

In [ ]:
# run this code to turn in your work!
from casstools.assignment import Assignment
Assignment().submit()